books/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from catalog.views import base
urlpatterns = [
    # path('', base),
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('addbook/', views.AddBooks.as_view(), name='addbook_url'),
    path('addauthor/', views.AddAuthor.as_view(), name='author_url'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('author/', views.Authors.as_view(), name='author'),
    path('search/', views.search, name='search'), 
    path('<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
]

catalog/models.py
from django.db import models
import os


class AddBook(models.Model):
    """Model definition for AddBook."""
    class Meta:
        """Meta definition for AddBook."""
        verbose_name = 'AddBook'
        verbose_name_plural = 'AddBooks'
        
    title = models.CharField(max_length=240)
    description = models.TextField()
    image = models.ImageField(upload_to='user_book/', blank=True)
    file_book = models.FileField(upload_to='file_book', null=True)
    
    def __str__(self):
        """Unicode representation of AddBook."""
        return self.title

    def delete(self):
        self.image.delete()
        super(AddBook, self).delete()


class Author(models.Model):
    """Model definition for Author."""
    class Meta:
        """Meta definition for Author.""" 
        verbose_name = 'Author'
        verbose_name_plural = 'Authors'
        
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=80)
    was_born = models.DateField()
    photo = models.ImageField(upload_to='author_book/', blank=True)
    book = models.ManyToManyField(AddBook)
    
    def __str__(self):
        """Unicode representation of Author."""
        return f'{self.first_name} {self.last_name}'

    def delete(self):
        self.image.delete()
        super(Author, self).delete()

catalog/forms.py
from django import forms
from catalog.models import AddBook, Author



class AddBooksForm(forms.ModelForm):
    """Form definition for AddBooks."""

    class Meta:
        """Meta definition for AddBooksform."""

        model = AddBook
        fields = "__all__"
        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'description':forms.Textarea(attrs={'class':'form-control'}),
        }


class AuthorForm(forms.ModelForm):
    """Form definition for Author."""
    class Meta:
        """Meta definition for Authorform."""
        model = Author
        fields = ('first_name', 'last_name', 'was_born', 'photo', 'book')
        widgets = {
            'first_name':forms.TextInput(attrs={'class':'form-control'}),
            'last_name':forms.TextInput(attrs={'class':'form-control', 'width':'20px'}),
            'was_born':forms.TextInput(attrs={'class':'form-control form-control-sm'}), 
            'book':forms.SelectMultiple(attrs={'multiple class':'form-control'})
        }

catalog/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic import TemplateView, View, DetailView
from catalog.models import AddBook, Author
from catalog.forms import AddBooksForm, AuthorForm
from django.db.models import Q


def base(request):
    return redirect(reverse('catalog:index'))


class IndexView(TemplateView):
    def get(self, request):
        books = AddBook.objects.all()
        return render(request, 'catalog/index.html', {'books':books})


class Authors(TemplateView):
    def get(self, request):
        author = Author.objects.all()
        return render(request, 'catalog/author_index.html', {'author':author})


class AddAuthor(View):
    def get(self, request):
        form = AuthorForm()
        return render(request, 'catalog/author.html', {'form':form})
        
    def post(self, request):
        form = AuthorForm(request.POST, request.FILES)
        if form.is_valid():
            if 'photo' in request.FILES:
                form.image = request.FILES['photo']
            form.save()
            return redirect(reverse('catalog:author'))
        else:
            print(form.errors)
        return render(request, 'catalog/author.html', {'form':form})

class AddBooks(View):
    def get(self, request):
        form = AddBooksForm()
        return render(request, 'catalog/addbook.html', {'form':form})

    def post(self, request):
        bound_form = AddBooksForm(request.POST, request.FILES)
        if bound_form.is_valid():
            if 'image' in request.FILES:
                bound_form.image = request.FILES['image']
            bound_form.save()
            return redirect(reverse('catalog:index'))
        else:
            print(bound_form.errors)
        return render(request, 'catalog/addbook.html', {'form':bound_form})


class BookDetail(View):
    def get(self, request, pk):
        book = get_object_or_404(AddBook, pk=pk)
        return render(request, 'catalog/book.html', {'book':book})


def edit(request, pk):
    book = get_object_or_404(AddBook, pk=pk)
    form = AddBooksForm(request.POST or None, instance=book)
    if form.is_valid():
        form.save()
        return redirect(reverse('catalog:index'))
    return render(request, 'catalog/edit.html', {'form':form})

def delete(request, pk):
    book = get_object_or_404(AddBook, pk=pk)
    if request.method == 'POST':
        book.delete()
        return redirect(reverse('catalog:index'))
    return render(request, 'catalog/confirm_delete.html', {'object':book})
def search(request):
    search_query = request.GET.get('search', '')
    if search_query == '':
        print('Not found')
    if search_query:
        books = AddBook.objects.filter(Q(title__icontains=search_query) | Q(description__icontains=search_query))
        author = Author.objects.filter(Q(first_name__icontains=search_query) | Q(last_name__icontains=search_query))
    else:
        books = AddBook.objects.all()
        author = Author.objects.all()
    return render(request, 'catalog/index.html', {
        'books':books,
        'author':author
        })

catalog/templates/catalog/addbook.html
{% extends 'base.html' %}

{% load static %}
{% block title %}
    Add Book
{% endblock %}
    



{% block body %}
<div class="container">
    <h1>Add book</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        {% for field in form %}
            <div class="form-group">
                
                {% if field.errors %}
                    <div class="alert alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}

                <h2>
                    {{ field.label }}
                </h2>
                    
                    {{ field }}
            </div>
        {% endfor %}
            <button class="btn btn-primary" value="submit">Add Book</button>
    </form>
</div>


{% endblock %}
    

catalog/templates/catalog/author.html
{% extends 'base.html' %}



{% block title %}
    Author Page
{% endblock title %}
    


{% block body %}
    <div class="container"><h1>Add Author</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    {% for field in form %}
        <div class="form-group">
            {% if field.errors %}
                    <div class="alert alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}

                    <h2>
                        {{ field.label }}
                    </h2>
                    
                    {{ field }}
                </div>
                {% endfor %}
                
                 
        <button class="btn btn-danger" type="submit">Add Author</button>
</form>
</div>
{% endblock body %}
    

catalog/templates/catalog/author_index.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    Authors
{% endblock title %}
    


{% block body %}
    

<br>

<a class="btn btn-secondary" href="{% url 'catalog:author_url' %}" style="margin-left: 15px;">+ Add Author</a>

<div class="container-fluid">
    <div class="container">
        <div class="row text-center">
            
            {% for a in author %}
            
           
            <div class="col"><img src="{{ MEDIA_URL }}{{ a.photo }}" width="150px" height="200px"><h5><br>{{ a.first_name }}</h5>{{ a.last_name }}    
            <br>  <br>    <strong>Books:</strong> 
            {% for b in a.book.all %}
                {{ b }}
            {% endfor %}
                 <hr></div>
                
            {% endfor %}
                
        </div>
    </div>
</div>

{% endblock body %}
    

catalog/templates/catalog/book.html
{% extends 'base.html' %}





{% block title %}
{{ book.title }}
{% endblock title %}



{% block body %}
<br>
<br>
<h1 class="h1_nan">
    {{ book.title }}
</h1>
<div class="container">
    <div class="d-flex">
        <div>
            <img src="{{ book.image.url }}" class="imga">
            <div class="aa">
                <a class="btn btn-primary" href="{% url 'catalog:edit' pk=book.pk %}">Edit</a>
                <a class="btn btn-danger" href="{% url 'catalog:delete' pk=book.pk %}">Delete</a>
            </div>
        </div>
        <div>
            <div class="description">{{ book.description }}</div>
            <h2 class="h_2">
                <strong>Authors:</strong>
                {% for au in book.author_set.all %}
                {{ au }}, 
                {% endfor %}
            </h2>
        </div>
    </div>
</div>

{% endblock body %}

catalog/templates/catalog/confirm_delete.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
<div class="row"></div>
<br/>
<div class="row">
<div class="col-md-2 col-xs-2 col-sm-2"></div>
	<div class="col-md-10 col-xs-10 col-sm-10">
		<form method="post">
			{% csrf_token %}
		  <div class="form-row">
		    <div class="alert alert-warning">
		    	Are you sure you want to delete {{ object }}?
		    </div>
		  </div>
		  <button type="submit" class="btn btn-danger">
		  	Delete
		  </button>
		</form>
	</div>
</div>
</div>
{% endblock %}

catalog/templates/catalog/edit.html
{% load widget_tweaks %}
{% include 'utils/navbar.html' %}

<!DOCTYPE html>
<html>
<head>
	<title>Edit Books</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<style type="text/css"></style>	
</head>
<body>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-1 col-xs-1 col-sm-1"></div>
		<div  class="col-md-10 col-xs-10 col-sm-10 ">
		<br/>
		</div>
		<div class="col-md-1 col-xs-1 col-sm-1">
		</div>
	</div>
	<div class="row">
		<div class="col-md-1 col-xs-1 col-sm-1"></div>
		<div class="col-md-10 col-xs-10 col-sm-10">
			<form method="post" novalidate>
			  {% csrf_token %}

			  {% for hidden_field in form.hidden_fields %}
			    {{ hidden_field }}
			  {% endfor %}

			  {% for field in form.visible_fields %}
			    <div class="form-group">
			      {{ field.label_tag }}
			      {% render_field field class="form-control" %}
			      {% if field.help_text %}
			        <small class="form-text text-muted">{{ field.help_text }}</small>
			      {% endif %}
			    </div>
			  {% endfor %}

			  <button type="submit" class="btn btn-primary">Edit</button>
			</form>
			<br>
		</div>
		<div class="col-md-1 col-xs-1 col-sm-1"></div>
	</div>
</div>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Index page
{% endblock title %}
{% block body %}
<br>
<a class="btn btn-primary" href="{% url 'catalog:addbook_url' %}" style="margin-left: 15px;">+ Add book</a>
<br>
<div class="container-fluid">
    <div class="container">
        <div class="row text-center">
            
            
        {% if books %}
            {% for n in books %}
                <div class="col"><a href="{% url 'catalog:book_detail' pk=n.pk %}"><img src="{{ MEDIA_URL }}{{ n.image }}" width="240px" height="320px"></a><h5><br><a href="{% url 'catalog:book_detail' pk=n.pk %}">{{ n.title }}</a></h5>{{ n.description }}<hr></div>
            {% endfor %}
                
        {% elif author %}
            {% for a in author %}
            <div class="col"><img src="{{ MEDIA_URL }}{{ a.photo }}" width="160px" height="220px"><h5><br>{{ a.first_name }}</h5>{{ a.last_name }}<hr></div> 
            {% endfor %}
        
        {% endif %}
            
        </div>
    </div>
</div>
</div>
{% endblock body %}
    
    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'icon/pngbarn.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700,900&display=swap" rel="stylesheet">

    <title>
        
        {% block title %}
            Base Page
        {% endblock %}
            
    </title>
</head>
<body>

        
    {% include 'utils/navbar.html' %}

      {% block body %}
          
      {% endblock %}
    <script src="{% static 'jquery/jquery.slim.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
          
</body>
</html>

templates/utils/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'catalog:index' %}">Books</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'catalog:author' %}">Authors <span class="sr-only">(current)</span></a>
        </li>
      </ul>
      <form method="GET" class="form-inline my-2 my-lg-0" action="{% url 'catalog:search' %}">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search">
        <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>